version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  retro_summary:
    build: .
    ports:
      - "8501:8501"

volumes:
  mongo_data:
