replicaCount: 1

image:
  repository: <your-docker-repo>/retrosummary
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8501

mongoUri: "mongodb://mongodb:27017"

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}